adesso network implementation
adessoTurkey/ios-boilerplate pull request #59
Opened 2020-12-29 11:50 UTC by firatyenidunya

2020-12-31 07:30 UTC, ismailkilic commented on ios-boilerplate/Network/BaseService.swift
> +    private let disposeBag = DisposeBag()
**disposeBag** kullanılmıyor class içerisinde

2020-12-31 07:34 UTC, ismailkilic commented on ios-boilerplate/Network/BaseService.swift
> +
Multipart requestler içinde bir yapı oluşturulmalı, alttakini örnek olarak attım, bu fonksiyon için handle ve public request fonksiyonlarıda oluşturulmalı

```
private func requestMultipart(with requestObject: RequestObject) -> UploadRequest {
        if requestObject.headers == nil {
            requestObject.headers = []
        }
        requestObject.headers?.add(HTTPHeader(name: "Content-type", value: "multipart/form-data"))
        return AF.upload(multipartFormData: { (multipartFormData) in
            if let parameter = requestObject.data?.dictionary {
                for (key, value) in parameter {
                    if let temp = value as? String {
                        multipartFormData.append(temp.data(using: .utf8)!, withName: key)
                    }
                    if let temp = value as? Int {
                        multipartFormData.append("\(temp)".data(using: .utf8)!, withName: key)
                    }
                    if let temp = value as? NSArray {
                        temp.forEach({ element in
                            let keyObj = key + "[]"
                            if let string = element as? String {
                                multipartFormData.append(string.data(using: .utf8)!, withName: keyObj)
                            } else
                            if let num = element as? Int {
                                let value = "\(num)"
                                multipartFormData.append(value.data(using: .utf8)!, withName: keyObj)
                            }
                        })
                    }
                }
            }
        }, to: requestObject.url,
        method: requestObject.method,
        headers: requestObject.headers,
        interceptor: requestObject.requestInterceptor)
    }
```

2020-12-31 07:40 UTC, firatyenidunya commented on ios-boilerplate/Network/BaseService.swift
> +
Selam ismail bu code çok uzun geldi bana çok anlayamadım. Daha önce şu şekilde çözmüştüm fakat progress completionını handle etme şeklimiz çok hoşuma gitmediğinden henüz buraya dahil etmedim.

Diğer handle fonksiyonları upload implement edildiğinde kullanılabilir aslında. Neden yenileri olmasını talep ettin farklı bir technical concern mü var o konuda?

    @discardableResult
    func upload<T: Decodable>(with uploadRequestObject: UploadRequestObject) -> Observable<Result<T>> {
        return Observable<Result<T>>.create { [unowned self] observer in
            uploadRequestObject.requestInterceptor = AuthInterceptor()
            uploadRequestObject.headers = self.createAuthenticatedHeaders(mergeWith: uploadRequestObject.headers ?? [])

            let request = self.upload(with: uploadRequestObject).responseDecodableObject { (response: AFDataResponse<T>) in
                                        self.handle(with: response, observer: observer )
            }
            return Disposables.create()
        }
    }

    private func upload(with uploadRequestObject: UploadRequestObject) -> UploadRequest {
        return AF.upload(
            multipartFormData: { multipartFormData in
                multipartFormData.append(uploadRequestObject.uploadData,
                                         withName: uploadRequestObject.dataName,
                                         fileName: uploadRequestObject.fileName,
                                         mimeType: uploadRequestObject.mimeType)
        },  to: uploadRequestObject.url,
            method: uploadRequestObject.method,
            headers: uploadRequestObject.headers,
            interceptor: uploadRequestObject.requestInterceptor)
    }

2021-02-26 11:45 UTC, akayrak-adesso commented on ios-boilerplate/Network/Entities/RequestObject.swift
> +class RequestObject {
Variables that have the same accessibility scope, should be grouped together.

2021-02-26 12:04 UTC, akayrak-adesso requested changes

2021-02-26 12:04 UTC, akayrak-adesso commented on ios-boilerplate/Network/Entities/RequestObject.swift
> +class RequestObject {
Variables that have the same accessibility scope, should be grouped together.

2021-02-26 12:04 UTC, akayrak-adesso commented on ios-boilerplate/Network/WebServices/ExampleService/ExampleServiceEnpoint.swift
> +                return Constants.exampleEndpoint + firstParameter + "/" + secondParameter
Parameterized/Pre-Formatted string for specific endpoint will be good to increase readability of endpoint.

2021-02-26 12:04 UTC, akayrak-adesso commented on ios-boilerplate/Network/WebServices/ExampleService/ExampleServiceEnpoint.swift
> +enum ExampleServiceEnpoint: TargetEndpointProtocol {
Typo in enum name, file name and comment: ExampleServiceEnpoint -> ExampleServiceEn**d**point

2021-02-26 12:04 UTC, akayrak-adesso commented on ios-boilerplate/Network/WebServiceRepositories/ExampleServiceRepository.swift
> +class ExampleServiceRepository: ExampleServiceRepositoryProtocol {
I think naming this with excluding the service keyword will be better. Because a repository should not necessarily be connected to just a service, it can be connected to local data storage or to something else. 

So, in the same manner, the `exampleRequest` function can be renamed to something like not associated with request eg. `getExample`.

2021-02-26 12:04 UTC, akayrak-adesso commented on ios-boilerplate/Network/WebServiceRepositories/ExampleServiceAdapter.swift
> +class ExampleServiceRepository: ExampleServiceAdapterProtocol {
In sample application adapter logic is replaced with use case. So to be consistent, either let's change this to use case, or exclude adapter logic from this scope.

2021-03-02 08:35 UTC, akayrak-adesso approved these changes

2021-03-02 08:37 UTC, merged